# FROM ubuntu:24.04
FROM postgres:16.4-alpine3.20

#RUN groupadd -g 1111 postgres && useradd -u 1111 -g 1111 -d /var/lib/postgresql -s /bin/bash postgres

#RUN apt update &&apt install -y postgresql-16 &&rm -rf /var/lib/apt/lists/*

COPY ./postgresql/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
