#!/bin/bash
set -e

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
# 	CREATE USER zabbix;
# 	CREATE DATABASE zabbix;
# 	GRANT ALL PRIVILEGES ON DATABASE zabbix TO zabbix;
# EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE zabbix;
	CREATE USER $POSTGRES_USER WITH SUPERUSER PASSWORD '$POSTGRES_PASSWORD';
	CREATE USER zabbix WITH PASSWORD 'zabbix';
	GRANT ALL PRIVILEGES ON DATABASE zabbix TO zabbix;
	ALTER DATABASE zabbix OWNER TO zabbix;
EOSQL
